//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppVenteRepeat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit1
    {
        public int idProduit { get; set; }
        public string codeProduit { get; set; }
        public string nomProduit { get; set; }
        public Nullable<double> prixUnitaire { get; set; }
        public Nullable<int> qteMin { get; set; }
        public Nullable<int> qteCri { get; set; }
        public string codeCategorie { get; set; }
    }
}
