//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppVenteRepeat.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profil
    {
        public int idProfil { get; set; }
        public string codeProfil { get; set; }
        public string nomProfil { get; set; }
    }
}
